security:
  oauth2:
    client:
      client-id: unif-support
      client-secret: pin
      user-authorization-uri: http://10.8.20.35:9191/oauth/authorize
      access-token-uri: http://10.8.20.35:9191/oauth/token
    resource:
      token-info-uri: http://10.8.20.35:9191/oauth/check_token

server:
  address: 10.8.20.35
  port: 9298
  servlet:
    session:
      cookie:
        name: KSESSION


in:
  co:
    srdt:
      unifsupport:
        theme: blue-grey
        api-gateway: http://localhost:7082
        zoolservernavbar: http://10.8.20.35:9191
        mailid: no-reply@srdt.co.in
        mailpass: Srdt@1234
        passresetsecret: tHiSk3yw11lreSE7p@55
        localurl: http://${server.address}:${server.port}